=== andreitode/l2j-clasic/dist/game/data/xsd/skillRoutes.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="skillRoutes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="skillRoute" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="skillId" type="xs:int"/>
                                        <xs:element name="routeId" type="xs:int"/>
                                        <xs:element name="name" type="xs:string"/>
										<xs:element name="description" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== andreitode/l2j-clasic/dist/game/data/skillRoutes.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/skillRoutes.xsd">
<skillRoutes>
    <skillRoute>
        <skillId>1</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>1</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes the skill's efficiency. Decreases MP consumption.</description></skillRoute>
    <skillRoute>
        <skillId>5</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>5</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes the skill's efficiency. Decreases MP consumption.</description></skillRoute>
    <skillRoute>
        <skillId>6</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>6</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes the skill's efficiency. Decreases MP consumption.</description></skillRoute>
    <skillRoute>
        <skillId>7</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>7</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes efficiency of skill. MP consumption decreases.</description></skillRoute>
    <skillRoute>
        <skillId>9</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>9</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes efficiency of skill. MP consumption decreases.</description></skillRoute>
    <skillRoute>
        <skillId>13</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes the skill’s power. Servitor’s power is increased.</description></skillRoute>
    <skillRoute>
        <skillId>17</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>17</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes efficiency of skill. MP consumption decreases.</description></skillRoute>
    <skillRoute>
        <skillId>18</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes the skill's power. Increases the power.</description></skillRoute>
    <skillRoute>
        <skillId>18</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes the skill's efficiency. Decreases MP consumption.</description></skillRoute>
    <skillRoute>
        <skillId>19</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>19</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes efficiency of skill. MP consumption decreases.</description></skillRoute>
    <skillRoute>
        <skillId>24</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>24</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes efficiency of skill. MP consumption decreases.</description></skillRoute>
    <skillRoute>
        <skillId>25</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes the skill’s power. Servitor’s power is increased.</description></skillRoute>
    <skillRoute>
        <skillId>28</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes the skill's power. Increases the power.</description></skillRoute>
    <skillRoute>
        <skillId>28</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes efficiency of skill. MP consumption decreases.</description></skillRoute>
    <skillRoute>
        <skillId>30</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>30</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes efficiency of skill. MP consumption decreases.</description></skillRoute>
    <skillRoute>
        <skillId>35</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>35</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes efficiency of skill. MP consumption decreases.</description></skillRoute>
    <skillRoute>
        <skillId>36</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>36</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes efficiency of skill. MP consumption decreases.</description></skillRoute>
    <skillRoute>
        <skillId>42</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Increased regeneration and a chance to absorb MP from a corpse.</description></skillRoute>
    <skillRoute>
        <skillId>42</skillId>
        <routeId>2001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Increased regeneration and a chance to absorb MP from a corpse.</description></skillRoute>
    <skillRoute>
        <skillId>46</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>46</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes the skill's efficiency. Decreases MP consumption.</description></skillRoute>
    <skillRoute>
        <skillId>48</skillId>
        <routeId>1001</routeId>
        <name>Chance</name>
    <description>Maximizes the skill’s success rate. Success rate increases.</description></skillRoute>
    <skillRoute>
        <skillId>48</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes the skill's efficiency. Decreases MP consumption.</description></skillRoute>
    <skillRoute>
        <skillId>49</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>49</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes efficiency of skill. MP consumption decreases.</description></skillRoute>
    <skillRoute>
        <skillId>51</skillId>
        <routeId>1001</routeId>
        <name>Cost</name>
    <description>Maximizes the skill's effectiveness. Increases attack range and decreases MP consumption/re-use time.</description></skillRoute>
    <skillRoute>
        <skillId>54</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>54</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes the skill's efficiency. Decreases MP consumption.</description></skillRoute>
    <skillRoute>
        <skillId>58</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>58</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes the skill's efficiency. Decreases MP consumption.</description></skillRoute>
    <skillRoute>
        <skillId>69</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>69</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes the skill's efficiency. Decreases HP consumption.</description></skillRoute>
    <skillRoute>
        <skillId>70</skillId>
        <routeId>1001</routeId>
        <name>Power</name>
    <description>Maximizes power of skill. Power Increases.</description></skillRoute>
    <skillRoute>
        <skillId>70</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
    <description>Maximizes the skill's efficiency. Decreases MP consumption.</description></skillRoute>
    <skillRoute>
        <skillId>72</skillId>
        <routeId>1001</routeId>
        <name>Time</name>
    <description>Maximizes the duration of the skill. Increases the duration.</description></skillRoute>
    <skillRoute>
        <skillId>72</skillId>
        <routeId>2001</routeId>
        <name>Cost</name>
